### ISSUE TITLE
The question of whether TestData in geoparse_dataset.py can run

### ISSUE THREAD

**Issue by Yvonne-sq** [geoai-lab/NeuroTPR#5]
Hello,

In geoparse_ dataset. py, file_ Path refers to the test data HarveyTweet2017. Because the format of the test data set is different from that of the training data set, a series of errors will occur when reading the file. Please ask whether geoparse_ dataset.py can  run and whether the test data upload is correct? If the test data format is correct, you can upload a geoparse_ dataset.py that can run?I would be grateful if Mr.Hu could give me a timely reply.

Thanks,
Yvonne

**Comment by YingjieHu** [comment]
Hi Yvonne,

 

Thank you for getting in touch!

 

Jimin Wang has graduated about two years ago, and we probably can’t address this technical issue now unfortunately. The pretrained model should still work, and you may also change the source code if you would like to train your own model.

 

Best wishes,
Yingjie

 

 

From: Yvonne-sq ***@***.***> 
Sent: Friday, December 9, 2022 4:51 AM
To: geoai-lab/NeuroTPR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geoai-lab/NeuroTPR] The question of whether TestData in geoparse_dataset.py can run (Issue #5)

 

In geoparse_ dataset. py, file_ Path refers to the test data HarveyTweet2017. Because the format of the test data set is different from that of the training data set, a series of errors will occur when reading the file. Please ask whether geoparse_ dataset.py can run and whether the test data upload is correct? If the test data format is correct, you can upload a geoparse_ dataset.py that can run?I would be grateful if Mr.Wang could give me a timely reply.

Traceback (most recent call last):
File "D:/Yvonne/yan_1/before/studio/learning_assignment/assigment_2/NeuroTPR-master/SourceCode/neurotpr/geoparse_dataset.py", line 136, in 
tag_corpus(model,file_path, word2Idx, inv_labelIdx, char2Idx, char2Idx_caseless, pos2Idx)
File "D:/Yvonne/yan_1/before/studio/learning_assignment/assigment_2/NeuroTPR-master/SourceCode/neurotpr/geoparse_dataset.py", line 107, in tag_corpus
sentences = readfile_nolabel(article_path)
File "E:\Miniconda\Miniconda3-py37\envs\NeuroTPR\lib\site-packages\neurotpr\prediction_pre.py", line 64, in readfile_nolabel
sentence.append([splits[0], current_index, splits[1], splits[2]])
IndexError: list index out of range
